#!/bin/bash

### Configuration
accentColor="#ff79c6"
separator="|"
useDesktopNames=false
###

checkForDesktopName() {
    if [[ $useDesktopNames = true ]]; then
        desktopLabel=$(wmctrl -d | awk '{$1=$2=$3=$4=$5=$6=$7=$8=$9="";print}' | sed 's/^[[:space:]]*//' | sed -n -e ${i}p)
    else
        desktopLabel=$i
    fi
}

numberOfDesktops=$(wmctrl -d | wc -l)
moduleText=""
desktopLabel=""
for i in $(seq 1 $numberOfDesktops); do
    s=$separator
    if [[ $i = $numberOfDesktops ]]; then
        s=""
    fi

    if [[ $i = $(qdbus org.kde.KWin /KWin currentDesktop) ]]; then
        checkForDesktopName
        moduleText+="%{F$accentColor}$desktopLabel%{F-} $s "
    else
        checkForDesktopName
        moduleText+=$desktopLabel" $s "
    fi
done

echo $moduleText
